#!/bin/busybox sh

/bin/busybox echo "installing symlinks..."

/bin/busybox --install -s

echo "installed symlinks"

mount -t devtmpfs devtmpfs /dev
mount -t proc procfs /proc
mount -t sysfs sysfs /sys

mkdir debugfs ; chmod 755 debugfs
mount -t debugfs debugfs /debugfs

mkdir /etc
mkdir /etc/init.d
cat > /etc/init.d/rcS <<!
#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done
!
chmod +x /etc/init.d/rcS
touch /etc/init.d/rcK
chmod +x /etc/init.d/rcK

cat <<!

Welcome to Linux!

Boot took $(cut -d' ' -f1 /proc/uptime) seconds

!

exec /bin/busybox init

echo "fell off end of init"
echo "launching shell"
setsid sh -c 'exec sh </dev/ttyS0 >/dev/ttyS0 2>&1'
echo "shutting down..."
busybox poweroff -f
