#!/bin/busybox sh

/bin/busybox echo "installing symlinks..."

/bin/busybox --install -s

echo "installed symlinks"

mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys

cat <<!

Welcome to Linux!

Boot took $(cut -d' ' -f1 /proc/uptime) seconds

!

exec sh
echo "fell off end of init"
echo "shutting down..."
busybox poweroff -f
