#!/bin/busybox sh

/bin/busybox echo "installing symlinks..."

/bin/busybox --install -s

echo "installed symlinks"

ls -l /
mount -t devtmpfs devtmpfs /dev
mount -t proc procfs /proc
mount -t sysfs sysfs /sys
ls -l /dev

mkdir debugfs ; chmod 755 debugfs
mount -t debugfs debugfs /debugfs


cat <<!

Welcome to Linux!

Boot took $(cut -d' ' -f1 /proc/uptime) seconds

!

exec /bin/busybox init

echo "fell off end of init"
echo "launching shell"
setsid sh -c 'exec sh </dev/ttyS0 >/dev/ttyS0 2>&1'
echo "shutting down..."
busybox poweroff -f
